# Generated by Django 4.2.8 on 2023-12-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('WIS', 'WIS'), ('LINCOLN', 'Lincoln'), ('DHS', 'DHS'), ('JEFFERSON', 'JEFFERSON'), ('GRANDVIEW', 'GRANDVIEW'), ('WILSON', 'WILSON'), ('JFK', 'JFK'), ('ROOSEVELT', 'ROOSEVELT')], default='DHS', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('tech', 'Tech'), ('regular', 'Regular User')], default='regular', max_length=10),
        ),
    ]
