# Generated by Django 4.2.8 on 2023-12-19 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_customuser_options_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tech_field_1', models.CharField(max_length=50)),
                ('tech_field_2', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('tech', 'Tech'), ('staff', 'Staff'), ('admin', 'Admin')], default='regular', max_length=10),
        ),
    ]
