# Generated by Django 4.2.8 on 2023-12-15 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done')], default='To Do', max_length=25)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('location', models.CharField(blank=True, choices=[('WIS', 'WIS'), ('LINCOLN', 'Lincoln'), ('DHS', 'DHS'), ('JEFFERSON', 'JEFFERSON'), ('GRANDVIEW', 'GRANDVIEW'), ('WILSON', 'WILSON'), ('JFK', 'JFK'), ('ROOSEVELT', 'ROOSEVELT')], max_length=20, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('Medium', 'Medium'), ('high', 'High')], default='Medium', max_length=25)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('tech_assigned', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tech_assigned', to=settings.AUTH_USER_MODEL)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tickets.tickettype')),
            ],
        ),
    ]
